server:
  port: 8080
  servlet:
    context-path: /trading-service
logging:
  level:
    root: INFO

trading:
  api-key: "YOUR_KITE_API_KEY"
  api-secret: "YOUR_KITE_API_SECRET"
  access-token: "YOUR_KITE_ACCESS_TOKEN"
  instrument-tokens: [ 256265, 738561 ]   # List of tokens trade
  bar-durations: [ 1, 3, 5 ]              # Bar sizes in seconds (for multiple resolutions)
  weka-model: "RandomForest"            # Could be RandomForest, J48, etc.
  #  historic-file-path: "src/main/resources/historical_data.csv"
  historic-file-path: "src/main/resources/2024-11-19.json"
  default-order-quantity: 1             # How many units/contracts per trade
  trade-product: "MIS"                  # MIS, CNC, NRML, etc.
  trade-exchange: "NSE"                 # NSE, BSE, etc.
  paper-trade: true                     # Set false for live trading
