server:
  port: 8080
  servlet:
    context-path: /trading-service

logging:
  level:
    root: INFO

trading:
  instrument-tokens: [ 256265, 738561 ]   # List of tokens trade
  profile:
    backtest:
      provider: "json"                      # Ex: "json" or "csv" or "api"
      json-path: "src/main/resources/sample_ticks.json"
      csv-path: "src/main/resources/historical_data.csv"
      api-instrument-token: 123456
      api-interval: "minute"                # Ex: "minute", "5minute"
      api-from: "2024-06-01"
      api-to: "2024-06-30"
    paper:
      paper-trade: true                     # Set false for live trading
    live:
      default-order-quantity: 1             # How many units/contracts per trade
      trade-product: "MIS"                  # Ex: MIS, CNC, NRML, etc.
      trade-exchange: "NSE"                 # Ex: NSE, BSE, etc.

zerodha:
  account:
    user-id: YS8604
  kite:
    api-key: "<KITE_API_KEY>"
    api-secret: "<KITE_API_SECRET>"
    request-token: "<KITE_REQUEST_TOKEN>"
    access-token: "<KITE_ACCESS_TOKEN>"
    public-token: "<KITE_PUBLIC_TOKEN>"
  ticker:
    try-reconnection: true
    max-retries: 10
    max-retry-interval-sec: 30

indicator:
  bar-durations: [ 1, 3, 5 ]              # Bar sizes in seconds (for multiple resolutions)

ml:
  model-name: "RandomForest"            # Ex: RandomForest, J48, etc.
