package invest.automate.trade.signal;

import invest.automate.trade.model.OrderType;
import invest.automate.trade.model.SignalType;
import lombok.Builder;
import lombok.Data;

/**
 * Represents a trading signal generated by a strategy.
 */
@Data
@Builder
public class Signal {
    private String instrumentToken;
    private SignalType type;
    private double price;
    private int quantity;
    private OrderType orderType;
}
